### PR TITLE
I have inserted last new parameter from google: PRIORITY

### PR DESCRIPTION
**Pull request by Samuel18**
13/08/2015

priority parameter;
aviable values: normal or high

Signed-off-by: Samuel Ventimiglia <sviluppo@tulain.com>

### CODE REVIEW

**Comment by Samuel18** [comment]
Thank you all

**Comment by Samuel18** [comment]
Tell me about if yes.

**Comment by Samuel18** [comment]
Unable to enable crypto on TCP connection gcm-http.googleapis.com: make sure the "sslcafile" or "sslcapath" option are properly set for the environment.

Error on my vps, so with simple parameter fix it

**Comment by Samuel18** [comment]
Tell me when i have to close pull request, please

**Comment by mwillbanks** [comment]
Unfortunately this pull request is not able to be merged in it's current form.  You adjusted the formatting on the client which changes each line and does not follow the coding standard.  In addition, you added several files that are not relevant to the project (.settings folder, .project and the additions to the .gitignore).  

This pull request is also missing unit tests for the added behavior and will need to be added before a merge can happen here.

**Pull request closed without merging**
