### PR TITLE
Support for FCM (#20)

### PR DESCRIPTION
**Pull request by kleisauke**
- Change GCM end-point to FCM
- Make Travis happy
- Test PHP 7.0 (#22)
- Add new parameters from FCM docs (#21) (https://firebase.google.com/docs/cloud-messaging/http-server-ref)
- Some PHP doc fixes
- Update PHPUnit
- Fix Travis for PHP 7 (#9)

### CODE REVIEW

**Comment by bathan** [comment]
@kleisauke  I think it would be best to create a Fcm folder and just duplicate everything and then change the endpoint url. It does not feel "right" to have a Gcm client pointing to the Fcm endpoint.

Just a thought.  I would also love to have FCM support. @mwillbanks

**Comment by mwillbanks** [comment]
I've added a develop branch against #27 I will be rebasing this against that and resolving any conflicts.  I hope that I can get this completed today.

**Comment by mwillbanks** [comment]
This has been merged to the develop branch for the next release.

**Comment by jaystepin** [comment]
@kleisauke I am agree with @bathan to add new folder for FCM.

**Comment by mwillbanks** [comment]
I'll merge it to master and release today.  Sorry for the delay.

**Pull request closed without merging**
